name: telegram_frontend
description: Telegram Flutter App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.0
  formz: ^0.8.0
  freezed_annotation: ^3.1.0
  go_router: ^16.1.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.16.0
  shared_preferences: ^2.5.3
  web_socket_channel: ^3.0.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.5.4
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/roboto/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          style: italic
